### PR TITLE
[WIP] Tooling

### PR DESCRIPTION
**Pull request by nhaesler**
This is a work in progress to replace bower with npm as a front-end package manager and grunt with npm scripts, while changing our project structure to achieve a maximally flat structure. Here be dragons.

### TODO
- [x] watch script
- [x] angular-gettext
- [x] obsolete build.sh, includes config.js and buildstamp.js generation
- [x] `npm start` as `npm run serve`?
- [x] lzma_worker.js wrapping

### CODE REVIEW

**Comment by addaleax** [comment]
Also see the bunch of PRs I made at [huston007/angular-gettext-cli](https://github.com/huston007/angular-gettext-cli) :)

**Comment by addaleax** [comment]
I’ve pushed a merge of master into #24 to `anna/tooling` (b0d57ba08d8b), but I can’t test it locally since apparently serving app/ does not work anymore? :/

**Comment by addaleax** [comment]
@nhaesler Feel free to merge if you like this! :)

**Comment by addaleax** [comment]
Plus, take a look at keithamus/parallelshell#44

**Comment by nhaesler** [comment]
How exactly is this bug affecting us? I was aware of mysticatea/npm-run-all#10, but chose parallelshell for the meantime, because it's the only library which really solves the problem of all processes exiting correctly.

**Pull request merged**
