### PR TITLE
fix issue #4

### PR DESCRIPTION
**Pull request by hieutran**

### CODE REVIEW

**Comment by addaleax** [comment]
I see that you added your own code to load the ranking and set up an `$scope.init` handler; I know that there is little to no documentation on this within the client code (and here, I am probably the one to blame), but previously, this worked a little differently:

When the user chose e.g. “Since 1 Week ago” in the drop-down menu, the angular router state parameters were changed in order to reload the entire ranking scope.

I don’t know how familiar you are with how angular-ui-router works, but essentially, the URI was changed from `…/ranking/all` to `…/ranking/all:1 week`.
`ranking.deserializeSpec` parses this format into $scope.spec, `ranking.serializeSpec` creates a string from `$scope.spec`.

So, when the 1-week-ago link was clicked, which looked something like `<a ui-sref=".({spec: csr({since: '1 week'})})" …>`, the `csr({since: '1 week'})})` part returned something like `all:1 week` and `ui-sref` (the angular-ui router equivalent of `href`) took the user to `…/ranking/all:1 week`, creating a new `$scope` where the time information was read from the state parameters.

This has the advantage that you can create links to rankings for specific time stamps, bookmark the current week’s ranking, etc.

I modified your changes to fit the previous mechanism in 2e35a4647e29561b6ad9c314478cc42f1b91a319, hope that’s fine with you.

**Comment by addaleax** [comment]
(I can see that there is currently still a bug occurring when you only pick the “until” date; This is my fault, so I’m going to fix that.)

**Comment by hieutran** [comment]
I did not pay attention and ignored the mechanism which provides ability to bookmark ranking links. It's my mistake.

**Comment by addaleax** [comment]
No, seriously, don’t blame yourself – there is nearly no documentation within the client code whatsoever. And if you’re uncertain about anything, just ask us :)

**Pull request merged**
